# Generated by Django 2.2 on 2019-05-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190526_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
