# Generated by Django 2.2 on 2019-06-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190531_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
